name: entangled 
channels:
  - conda-forge
dependencies:
  - freud
  - gsd
  - hoomd<4.0=*cpu*
  - matplotlib
  - mbuild
  - mdanalysis
  - mbuild
  - numpy
  - pip
  - pymbar >= 4.0
  - python<3.11
  - pytest
  - pytest-cov
  - rowan
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
